(()=>{'use strict';
const KEY='reason-engine-atlas-v01';
const EXAMPLE='Wir müssen ungefähr 50 Weihnachtsbäume im Krankenhaus verteilen. Bisher werden die Standorte auf einem alten Holzbrett notiert, auf dem noch Häkchen aus mehreren Jahren stehen. Änderungen gehen verloren, Zuständigkeiten sind unklar und am Ende weiß niemand sicher, ob jeder Baum am richtigen Ort steht.';
const Q=['Wer ist an diesem Problem beteiligt oder davon betroffen?','Was wäre ein gutes, überprüfbares Ergebnis?','Welche Regeln, Grenzen oder Ressourcen müssen berücksichtigt werden?','Wie läuft der Prozess heute tatsächlich ab, Schritt für Schritt?','Wo entsteht momentan der größte Verlust, Konflikt oder Zeitaufwand?','Welche Entscheidung muss als Nächstes getroffen werden?'];
const $=(s)=>document.querySelector(s),$$=(s)=>[...document.querySelectorAll(s)];
const screens=$$('[data-screen]'),problem=$('#problem-input'),chat=$('#chat-input'),messages=$('[data-messages]'),nodes=$('[data-nodes]'),lines=$('[data-lines]'),title=$('[data-title]'),dialog=$('[data-node-dialog]');
const nodeKind=$('[data-node-kind]'),nodeTitle=$('[data-node-title]'),nodeBody=$('[data-node-body]'),nodeStatus=$('[data-node-status]'),nodeSource=$('[data-node-source]');
let selected=null,state=load();
function id(){return Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8)}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x&&x.version==='0.1'?x:null}catch(e){console.warn(e);return null}}
function save(){if(state)localStorage.setItem(KEY,JSON.stringify(state))}
function show(name){screens.forEach(x=>x.hidden=x.dataset.screen!==name);window.scrollTo(0,0)}
function short(text,n=58){const s=text.replace(/\s+/g,' ').trim().split(/[.!?]/)[0];const w=s.split(' ').slice(0,8).join(' ');return w.length>n?w.slice(0,n-1)+'…':w||'Neuer Atlas'}
function pos(i){const p=[[50,10],[88,34],[87,68],[50,88],[12,68],[12,34],[35,27],[68,28],[68,67],[34,68]][i%10];return{x:p[0],y:p[1]}}
function initial(text){const t=short(text);return{version:'0.1',createdAt:new Date().toISOString(),title:t,problem:text,step:0,messages:[{id:id(),role:'engine',text:'Ich habe den Ausgangspunkt als vorläufigen Problemraum angelegt. Nichts davon gilt automatisch als bestätigt.'},{id:id(),role:'engine',text:Q[0]}],nodes:[{id:'root',title:t,body:text,kind:'root',confirmed:true,source:'Ursprüngliche Problembeschreibung',x:50,y:48},{id:id(),title:'Beteiligte',body:'Noch nicht geklärt.',kind:'open',confirmed:false,source:'Vorgeschlagener Klärungsraum',x:18,y:18},{id:id(),title:'Gewünschtes Ergebnis',body:'Noch nicht geklärt.',kind:'open',confirmed:false,source:'Vorgeschlagener Klärungsraum',x:78,y:18},{id:id(),title:'Rahmenbedingungen',body:'Noch nicht geklärt.',kind:'open',confirmed:false,source:'Vorgeschlagener Klärungsraum',x:18,y:76},{id:id(),title:'Nächste Entscheidung',body:'Noch nicht geklärt.',kind:'open',confirmed:false,source:'Vorgeschlagener Klärungsraum',x:78,y:76}]}}
function classify(text){const s=text.toLowerCase();if(s.includes('?')||/\b(unklar|weiß nicht|offen|keine ahnung)\b/.test(s))return'open';if(/\b(vielleicht|vermutlich|wahrscheinlich|ich glaube|ich denke|könnte|dürfte)\b/.test(s))return'assumption';if(/\b(entschieden|entscheidung|wir machen|wir nehmen|festgelegt|muss|soll|verantwortlich ist)\b/.test(s))return'decision';return'known'}
function label(k){return{root:'Ausgangspunkt',known:'Aussage · unbestätigt',assumption:'Annahme · unbestätigt',open:'Offene Frage',decision:'Entscheidung · unbestätigt'}[k]||'Eintrag'}
function add(text){const kind=classify(text),p=pos(state.nodes.length-1);state.nodes.push({id:id(),title:short(text,46),body:text,kind,confirmed:false,source:'Direkte Eingabe im Gespräch',x:p.x,y:p.y});state.messages.push({id:id(),role:'user',text});const ack={open:'Ich habe das als offene Frage markiert, nicht als Tatsache.',assumption:'Ich habe das als Annahme markiert. Sie bleibt sichtbar unbestätigt.',decision:'Ich habe das als vorläufige Entscheidung markiert. Sie ist noch nicht bestätigt.',known:'Ich habe das als direkte Aussage aufgenommen. Sie ist noch nicht bestätigt.'}[kind];state.messages.push({id:id(),role:'engine',text:ack});state.step=Math.min(state.step+1,Q.length);state.messages.push({id:id(),role:'engine',text:state.step<Q.length?Q[state.step]:'Der erste Gesprächsbogen ist vollständig. Öffne Atlas-Einträge, um sie zu prüfen, zu bestätigen oder zu entfernen.'});save();render()}
function render(){if(!state)return;title.textContent=state.title;renderMessages();renderNodes()}
function renderMessages(){messages.replaceChildren();state.messages.forEach(m=>{const a=document.createElement('article');a.className='message '+m.role;const l=document.createElement('small');l.textContent=m.role==='engine'?'Reason Engine':'Du';const p=document.createElement('p');p.textContent=m.text;a.append(l,p);messages.append(a)});requestAnimationFrame(()=>messages.scrollTop=messages.scrollHeight)}
function renderNodes(){nodes.replaceChildren();lines.replaceChildren();state.nodes.forEach(n=>{const b=document.createElement('button');b.type='button';b.className='node'+(n.kind==='root'?' root':'');b.dataset.kind=n.kind;b.dataset.confirmed=String(!!n.confirmed);b.style.left=n.x+'%';b.style.top=n.y+'%';b.style.transform='translate(-50%,-50%)';const k=document.createElement('span');k.className='node-kind';k.textContent=label(n.kind);const h=document.createElement('strong');h.textContent=n.title;const p=document.createElement('p');p.textContent=n.body;b.append(k,h,p);b.addEventListener('click',()=>openNode(n.id));nodes.append(b);if(n.id!=='root'){const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1','50%');line.setAttribute('y1','48%');line.setAttribute('x2',n.x+'%');line.setAttribute('y2',n.y+'%');lines.append(line)}})}
function openNode(i){const n=state.nodes.find(x=>x.id===i);if(!n)return;selected=i;nodeKind.textContent=label(n.kind);nodeTitle.textContent=n.title;nodeBody.textContent=n.body;nodeStatus.textContent=n.confirmed?'Bestätigt':'Vorläufig / unbestätigt';nodeSource.textContent=n.source;$('[data-confirm]').hidden=n.kind==='root'||n.confirmed;$('[data-delete]').hidden=n.kind==='root';dialog.showModal()}
function exportState(){const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(state.title.toLowerCase().replace(/[^a-z0-9äöüß]+/gi,'-').replace(/^-|-$/g,'')||'atlas')+'.json';document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url)}
$('[data-start]').addEventListener('click',()=>{show(state?'workspace':'problem');if(state)render();else problem.focus()});
$('[data-example]').addEventListener('click',()=>{problem.value=EXAMPLE;problem.focus()});
$('[data-problem-form]').addEventListener('submit',e=>{e.preventDefault();const text=problem.value.trim();if(text.length<20)return;state=initial(text);save();show('workspace');render()});
$('[data-chat-form]').addEventListener('submit',e=>{e.preventDefault();const text=chat.value.trim();if(!text)return;chat.value='';add(text)});
$('[data-export]').addEventListener('click',exportState);
$('[data-reset]').addEventListener('click',()=>{if(!confirm('Diesen lokalen Atlas vollständig löschen und neu beginnen?'))return;localStorage.removeItem(KEY);state=null;problem.value='';show('problem');problem.focus()});
$('[data-close]').addEventListener('click',()=>dialog.close());
$('[data-confirm]').addEventListener('click',()=>{const n=state.nodes.find(x=>x.id===selected);if(!n)return;n.confirmed=true;n.source+='; vom Nutzer bestätigt';state.messages.push({id:id(),role:'engine',text:'„'+n.title+'“ wurde als bestätigt markiert.'});save();dialog.close();render()});
$('[data-delete]').addEventListener('click',()=>{const n=state.nodes.find(x=>x.id===selected);if(!n||n.id==='root'||!confirm('Eintrag „'+n.title+'“ entfernen?'))return;state.nodes=state.nodes.filter(x=>x.id!==selected);state.messages.push({id:id(),role:'engine',text:'Der Atlas-Eintrag „'+n.title+'“ wurde entfernt. Die Gesprächsnachricht bleibt erhalten.'});save();dialog.close();render()});
$$('[data-tab]').forEach(b=>b.addEventListener('click',()=>{$$('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('[data-panel]').forEach(x=>x.classList.toggle('active',x.dataset.panel===b.dataset.tab));if(b.dataset.tab==='chat')chat.focus()}));
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
if(state){show('workspace');render()}else show('intro');
})();
